### ISSUE TITLE
API Issues Collection

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#269]
## Tasks

- [x] Document Files Versions API
- [x] Move Notifications API docs to dev docs (#2162)
- [ ] OCS Share API Documentation Incomplete

---
## Document Files Versions API

Opened by @DeepDiver1975 in https://github.com/owncloud/documentation/issues/3468

- [ ] How to list versions of a file (perform PROPFIND to /remote.php/dav/meta/$fileid/v)
- [ ] How to restore a version: (`COPY /remote.php/dav/meta/$fileid/v/$versionid /remote.php/dav/files/$user/foo/bar`)

**Note:** will be merged to master first - we need to decide when to merge this to 10.0.x

PR: owncloud/core#29207

## Move Notifications API docs to dev docs

Opened by @pmaier1 (https://github.com/owncloud/documentation/issues/3242)

As the headline says:

- https://github.com/owncloud/notifications/blob/master/docs/ocs-endpoint-v1.md
- https://github.com/owncloud/notifications/blob/master/docs/notification-workflow.md

## OCS Share API documentation incomplete

Opened by @moscicki (https://github.com/owncloud/documentation/issues/2212)

The doc is not specific about arguments (e.g., what a boolean is). It misses the spec of the XML response body. And examples of requests/responses. Documented examples may be validated automatically. Here is the example how we do it for the sync protocol. This script [1] validates PROPFIND responses documented in [2].

Please also consider the testing suggestion referenced in owncloud/pyocclient#154. See owncloud/core#22839 for a few more cases and examples. For a start see https://gist.github.com/rullzer/585d752cbda6be453e5a and paste that into http://editor.swagger.io/. I'm not saying we have to settle on this format, but @LukasReschke had some specs to start from.

Looks like a move in a nice direction. Can these specs somehow be used for automated validation of software that implements them?

On Thu, Mar 17, 2016 at 9:24 AM, Roeland Douma notifications@github.com
wrote:

> For a start see https://gist.github.com/rullzer/585d752cbda6be453e5a and paste that into http://editor.swagger.io/

[1]: https://github.com/cernbox/smashbox/blob/master/protocol/test_protocol_doc.py
[2]: https://github.com/cernbox/smashbox/blob/master/protocol/protocol.md

**Comment by settermjd** [comment]
How to list versions of a file (perform PROPFIND to /remote.php/dav/meta/$fileid/v)
How to restore a version: (COPY /remote.php/dav/meta/$fileid/v/$versionid /remote.php/dav/files/$user/foo/bar)

These are already documented in https://doc.owncloud.com/server/10.3/developer_manual/webdav_api/files_versions.html. However, the existing documentation is quite minimal. I'll flesh out the information today.
