### ISSUE TITLE
Document how to Integrate ownCloud into MS-Teams

### ISSUE THREAD

**Issue by fschade** [owncloud/docs#3387]
## WHAT Needs to be Documented?
How to integrate ownCloud 10 into MSTeams

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/latest/admin_manual/configuration/integration/microsoft-teams

## WHY Should This Change Be Made?
No changes, we need to document a new feature which shows how to use ownCloud from within teams

## (Optional) What Type Of Content Change Is This? 
- [X] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [X] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

# todos
- [ ] check, if admins can predefine apps for specific users
- [ ] MS Teams Bridge: update link to documentation in info.xml
- [ ] evaluate: how to make it more easy for admins to update the .htaccess (occ and config.php) within an update of ownCloud
- [ ] Azure-Button Label "Login to ownCloud"
- [ ]  Add bridge-app description here: https://github.com/owncloud/core/blob/master/config/config.apps.sample.php

# Input for Doc's Team
with 10.7 we created a few tools and updated some code from ownCloud to make it able to be displayed and be used from within MSTeams. 

## Use cases
access your private or organizations ownCloud installation from your existing MSTeams account. The clue here is that expect others we decided to create a generator that creates a customized MSTeams AppSource App for your individual ownCloud installation hosted on your private domain. That's something that differentiate our solution from others. 

## Configuration
Overall we have 3 parties that needed to be configured to get it up and running.
- MSAzure AD
  - here we need to setup a custom app that is needed for openidconnect
- ownCloud
  - openidconnect 2.0.0 app [github (it has a own README with useful tips)](https://github.com/owncloud/openidconnect), [marketplace](https://marketplace.owncloud.com/apps/openidconnect)
  - NEW: msteamsbridge 1.0.0 app [github (it has a own README with useful tips)](https://github.com/owncloud/msteamsbridge/), marketplace coming soon.
- MSTeams
- app that is generated by [msteamsgen](https://github.com/owncloud/msteamsgen)

### Azure (same setup applies to openidconnect app)
( please extend the OICD Doc with Azure as follows: )

- Login to [Azure](https://portal.azure.com/#home)
- GoTo [Manage Azure Active Directory](https://gist.githubusercontent.com/fschade/c6647ed1b8a0c1349bbaac962322fd4a/raw/de861205ccd84348df5759e5c00d6655cfb49cb5/msteams_1.png)
- Then go to "app registrations" and click [new registration](https://gist.githubusercontent.com/fschade/c6647ed1b8a0c1349bbaac962322fd4a/raw/eac771a80ac267fbe96666969ab80ee5deb980fa/msteams_2.png)
- provide all required information [there](https://gist.githubusercontent.com/fschade/c6647ed1b8a0c1349bbaac962322fd4a/raw/1f3d2bfde55fd39a0587b64a4ba6ba56751411f1/msteams_3.png)
- GoTo Authentication and setup your [redirect url](https://gist.githubusercontent.com/fschade/c6647ed1b8a0c1349bbaac962322fd4a/raw/d49c43727ed5e454bf87ea6eb6d3bd172fc6a8ca/msteams_4.png)
- GoTo Certificates & secrets and [setup a Client secret](https://gist.githubusercontent.com/fschade/c6647ed1b8a0c1349bbaac962322fd4a/raw/5853ab269b2754d8cfc49b40bd602e2524050b78/msteams_5.png) for your app
- GoTo token configuration and setup the [claims](https://gist.githubusercontent.com/fschade/c6647ed1b8a0c1349bbaac962322fd4a/raw/6220e2c84942f9783a27bc9453faa31776c26998/msteams_6.png)
- GoTo API permissions and add [following delegated graph permissions](https://gist.githubusercontent.com/fschade/c6647ed1b8a0c1349bbaac962322fd4a/raw/bc3621dfc0fcbbed1f52f54e15ebf88d3c92cf1a/msteams_7.png)
- At the same page please do not forget to [grant admin consent](https://gist.githubusercontent.com/fschade/c6647ed1b8a0c1349bbaac962322fd4a/raw/0d7f10879f19ccf809a5539492fffc93ae45e3fd/msteams_8.png) to all permissions
- GoTo "Expose an API" and set [Application ID URI](https://gist.githubusercontent.com/fschade/c6647ed1b8a0c1349bbaac962322fd4a/raw/1daccecf6356c6d65e950c747e8543138fdc0253/msteams_9.png)
- Then on the same page add a scope with name ["owncloud" and allow admins and users to consent](https://gist.githubusercontent.com/fschade/c6647ed1b8a0c1349bbaac962322fd4a/raw/21f978b8cc2735f7d60cf38a9fcbf5451a06f0d2/msteams_10.png)
- You get the CLIENT-ID after you've completed the MS Azure Setup process

### ownCloud
- install ownCloud
- install openidconnect 2.0.0 app 
- install msteamsbridge 1.0.0 app
- enable rewrites (e.g. apache mod_rewrite) /index.php/foo/bar => /foo/bar (see [index_php_less_urls](https://doc.owncloud.com/server/10.7/admin_manual/configuration/server/index_php_less_urls.html))
- apply the following header configuration (ownCloud .htaccess): 
```apacheconf
Header add Content-Security-Policy "frame-ancestors teams.microsoft.com *.teams.microsoft.com"
```
- apply the required ownCloud configuration with above values from azure for openid-connect and set samesite cookie to 'None'
```php
<?php
$CONFIG = [
    'http.cookie.samesite' => 'None',
    'openid-connect' => [
        'provider-url' => 'https://login.microsoftonline.com/YOUR-DIRECTORY-TENANT-ID/v2.0/',
        'client-id' => 'YOUR-CLIENT-ID',
        'client-secret' => 'YOUR-CLIENT-SECRET',
        'loginButtonName' => 'Azure AD',
        'autoRedirectOnLoginPage' => false,
        'scopes' => [
            'openid',
            'api://YAOR-APPLICATION-ID-SCOPE-URI/owncloud',
            'profile', 'email', 'offline_access',
        ],
        'mode' => 'email',
        'search-attribute' => 'unique_name',
        'use-access-token-payload-for-user-info' => true,
        'auto-provision' => [
            'enabled' => true,
            'email-claim' => 'email',
            'display-name-claim' => 'email',
        ],
    ],
];

```
### MS Teams (as Admin )
- In MS Teams AppSource: search for "ownCloud Generator for Admins" and open the Application
- once opened, please follow the guided steps.
- hint: name your App eg. "ownCloud for Teams"
- all steps are described on top of every step, the id MUST be the [APLLICATION-ID](https://gist.githubusercontent.com/fschade/c6647ed1b8a0c1349bbaac962322fd4a/raw/6eb955f428c375c39e4170d0a89ca09c68f2cf8a/msteams_11.png) from AZURE and the [url](https://gist.githubusercontent.com/fschade/c6647ed1b8a0c1349bbaac962322fd4a/raw/6eb955f428c375c39e4170d0a89ca09c68f2cf8a/msteams_12.png) MUST be your private owncloud installation url
- after all steps are finished press the download button and keep the generated zip file locally
- go back to the app section of MSTeams again and [upload](https://gist.githubusercontent.com/fschade/c6647ed1b8a0c1349bbaac962322fd4a/raw/633382d4ee7f5e9a65d5ec3ede0839124b389e2f/msteams_13.png) the generated zip from the step before 
- after this is done, upload the resulting zip file to your company's AppSource
- MS docs about upload apps to the AppSource Store: https://docs.microsoft.com/en-us/microsoftteams/manage-apps and: https://docs.microsoft.com/en-us/microsoftteams/upload-custom-apps
- (check, if admins can predefine apps for specific users )

### MS Teams (as consuming user)
- login to [MSTeams](https://teams.microsoft.com/)
- search for our app "ownCloud for Teams" (or the name provided by your Admin)
- hint: you can pin the app to your left sidebar permanently: rightclick -> pin
![image](https://user-images.githubusercontent.com/26610733/113852868-4d736580-979d-11eb-9cf6-bb34ff8e0d7d.png)
- login by clicking "Login to ownCloud with Azure AD"
- for security reasons you have to repeat the login process after idle time

## Support
- supply contact infos for help ( support@owncloud.com, central.owncloud.com )

As for the submission in AppSource, Microsoft requires from us to offer contact information for support. This is a requirement. lets discuss how we can integrate this requirement in our processes / oc-universe.
![image](https://user-images.githubusercontent.com/26610733/113829446-ce266780-9785-11eb-88ce-aa8756bba37e.png)

**Comment by ChrisEdS** [comment]
Do we need single quotes?
For example 
        'auto-provision' => [
            'enabled' => true,
            'email-claim' => 'email',
            'display-name-claim' => 'email',
        ],
        
        and 
        
            "openid-connect" => [
        "provider-url" => "https://login.microsoftonline.com/YOUR-DIRECTORY-TENANT-ID/v2.0/",
        "client-id" => "YOUR-CLIENT-ID",
        "client-secret" => "YOUR-CLIENT-SECRET",
        "loginButtonName" => "Azure AD",
        "autoRedirectOnLoginPage" => false,
        "scopes" => [
            "openid",
            "api://YAOR-APPLICATION-ID-SCOPE-URI/owncloud",
            "profile", "email", "offline_access",
        ],
        
looks inconsitent.

**Comment by fschade** [comment]
> Do we need single quotes?
> For example
> 
> ```
>         'auto-provision' => [
>             'enabled' => true,
>             'email-claim' => 'email',
>             'display-name-claim' => 'email',
>         ],
> ```
> 
> and
> 
> ```
>       "openid-connect" => [
>         "provider-url" => "https://login.microsoftonline.com/YOUR-DIRECTORY-TENANT-ID/v2.0/",
>         "client-id" => "YOUR-CLIENT-ID",
>         "client-secret" => "YOUR-CLIENT-SECRET",
>         "loginButtonName" => "Azure AD",
>         "autoRedirectOnLoginPage" => false,
>         "scopes" => [
>             "openid",
>             "api://YAOR-APPLICATION-ID-SCOPE-URI/owncloud",
>             "profile", "email", "offline_access",
>      ],
> ```
> 
> looks inconsistent.

good catch, done. I think it's finally time to convert the draft into a real thing. @pmaier1 any concerns?

**Comment by fschade** [comment]
@tbsbdr, can you double check aboves howTo please. for example we mention that the app is called "ownCloud generator for Teams" but i do not know the final name which we submitted to the appsource store.

**Comment by tbsbdr** [comment]
> ownCloud generator for Teams

"ownCloud for Teams" is the submitted name in the appsource store. corrected it in the description above.

**Comment by fschade** [comment]
@tbsbdr, @pmaier1 i removed draft state, in my opinion we are good to start documenting this.

**Comment by tbsbdr** [comment]
@fschade as discussed, could you please update / add:
- [ ] Azure-Button Label "Login to ownCloud"
- [ ] Add bridge-app description here: https://github.com/owncloud/core/blob/master/config/config.apps.sample.php

**Comment by pmaier1** [comment]
>  Azure-Button Label "Login to ownCloud"

@tbsbdr @fschade Just a hint: I think it is possible that users do not need to click the button by setting `autoRedirectOnLoginPage` to `true` in the OIDC config (https://doc.owncloud.com/server/admin_manual/configuration/user/oidc/#list-of-openid-connect-config-php-parameters). Does that work in our scenario and should we recommend it?

**Comment by fschade** [comment]
> > Azure-Button Label "Login to ownCloud"
> 
> @tbsbdr @fschade Just a hint: I think it is possible that users do not need to click the button by setting `autoRedirectOnLoginPage` to `true` in the OIDC config (https://doc.owncloud.com/server/admin_manual/configuration/user/oidc/#list-of-openid-connect-config-php-parameters). Does that work in our scenario and should we recommend it?

please do not use redirect, as we are using teams sdk a real user interaction should happen.

https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad#initiate-authentication-flow

```
... Authentication flow should be triggered by a user action. You should not open the authentication pop-up automatically because this is likely to trigger the browser's pop-up blocker as well as confuse the user. ...
```

**Comment by pmaier1** [comment]
Looking at https://github.com/owncloud/docs/pull/3467 I think we need to update the doc links in the `msteamsbridge` info.xml and anywhere else where it's used. @tbsbdr FYI

https://github.com/owncloud/msteamsbridge/pull/18
