### ISSUE TITLE
[ownBrander] Included new Desktop branded options

### ISSUE THREAD

**Issue by rperezb** [owncloud/docs#385]
Hey @carlaschroder this will be released, around 1st June:
- [ ] ubuntu 16.04 support https://github.com/owncloud/ownbrander/issues/602
- [ ] Show the quota information for a different folder than the root https://github.com/owncloud/ownbrander/issues/593
- [ ]  Server url hint https://github.com/owncloud/ownbrander/issues/587
- [ ]  Enable/Disable sharing options https://github.com/owncloud/ownbrander/issues/580
- [ ] Fix partially the server url https://github.com/owncloud/ownbrander/issues/577
- [ ] Allow/don't modify proxie settings https://github.com/owncloud/ownbrander/issues/572
- [ ] Modify userID wording https://github.com/owncloud/ownbrander/issues/569

**Comment by michaelstingl** [comment]
Documentation is in the ownBrander itself
