### ISSUE TITLE
Make a complete doc dev/testing environment

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#4874]
To do major Antora or UI upgrades, we need for all doc repos a dev version where we can safely play around without messing up production. This includes also, that the current `push-to-web` is then a `push-to-staging`.

**Affected repos:**

* docs*
* docs-main (upcoming, needs to be created first, see separate issue)

When created, we can copy the content from each repo to dev and adapt the pipeline accordingly making it ready for upgrade testing.

If there is a need to update a dev repo, we can just copy - without the pipeline - all data from production.

**Tasks:**

- [ ] Inform sysadmin to create new **private** `dev-docs*` repos with the same setup as production
- [ ] In the repo settings, allow merging PR's without approval
- [ ] Copy content from each production to dev repo
- [ ] Adapt in each dev repo the pipeline to push rendered content against staging

**Comment by xoxys** [comment]
That's a pretty bad approach... Using 20+ repos (!) to build a single static page for docs is simply... crazy. Just use a dev branch and learn how to use a local container stack for development, like the UI/Antora/Scripts etc. development has been done successfully for the last 4 years.

**Comment by mmattel** [comment]
I have to test the chain including the UI, not only a single repo and the target of building must not end up in production but in staging. There are bigger changes on the road that need an independent dev and testing env that must not disturb doc production. The full line is affected.

**Comment by mmattel** [comment]
Post a discussion with @xoxys we found a solution.

The task is done with #4907 (Update dev doc section and add search) and is part of #4853 (Upgrade the documentation framework) where the progess is documented ongoing.
