### ISSUE TITLE
Keep upgraded shipped apps on upgrade (hotfix/patch releases)

### ISSUE THREAD

**Issue by PVince81** [owncloud/docs#828]
Whenever a patch/hotfix release of the core or enterprise bundle is provided, an admin should upgrade to it.

The expectation is that such patch/hotfix release will cause minimal downtime.

The following situation could occur, on offline instances:

1. Admin installed owncloud-enterprise-complete 10.1.0
1. Admin updated non-shipped app "activity" app from 2.4.1 to 2.4.2 using marketplace download
1. Admin updated shipped app "firewall" from 0.7.0 to 0.8.0 using marketplace
1. Admin sets instance to be offline (no more marketplace contact)
1. A hotfix release comes out, owncloud-enterprise-complete 10.1.1. As it's a hotfix, it only provides the same app versions as 10.1.0 did. So firewall is 0.7.0 and activity is 2.4.1.
1. Admin does a [manual upgrade according to docs](https://doc.owncloud.com/server/admin_manual/maintenance/manual_upgrade.html#the-power-user-upgrade). This brings back the old versions of activity and firewall.
1. At this point the database states that we're on activity 2.4.2 and firewall 0.8.0 but as we're offline, there is no way to upgrade. The system is in an inconsistent state.
1. According to the [copy apps steps in doc](https://doc.owncloud.com/server/admin_manual/maintenance/manual_upgrade.html#copy-old-apps), the admin should copy third party apps back into the apps folder.

Expected: the last step should also mention any other upgraded apps.
Actual: the last step only mentions third party apps.

Additionally, it will be difficult for an admin to distinguish what apps were upgraded or not.
Ideally we should move to always recommend the separation of **shipped apps** from **upgraded** and **third party** apps by using [custom app directories](https://doc.owncloud.com/server/10.1/admin_manual/installation/apps_management_installation.html#using-custom-app-directories).

For now I suggest we adjust the documentation to be clear about the need to keep a backup of the updated apps repo. Maybe tell the admin to run `occ apps:list` to find out about app version discrepancies. Sadly the list doesn't help to distinguish between updated apps and not updated ones. Might need some FS scraping...

This needs to be written in a way that leaves **no room for surprises** as it's easy to get confused.

@pmaier1 @individual-it @mmattel @settermjd 

@voroyam FYI

**Comment by PVince81** [comment]
- [ ] tool/command to detect upgraded shipped apps: https://github.com/owncloud/core/issues/32048

**Comment by PVince81** [comment]
at step 7 the system will lock itself due to inconsistent state and will prompt admin to run `occ upgrade`.

for patch releases we want to avoid that, hence the proposed solutions:
- update of docs for preparint apps
- future solution about apps-external folder

**Comment by mmattel** [comment]
Regardin the term `shipped`:
Part from the referenced issue above, PR https://github.com/owncloud/core/pull/34563 (getAppsInTar) addresses the issue to distinguish apps between marked shipped (wrong use of the term shipped, you cant disable them) and apps part of tar release file (which is what we are looking for).

Looking to the possibility having any apps directory being a symlink for ease of handling, this would mean you can reuse the existing link with all apps in the latest state. 
But for the other cases, as @PVince81 stated, we `Might need some FS scraping...`

My question is, why don´t we create a `occ apps:check-version` command to check if the app versions in the database and in the filesystem match and add a option to fix the database? It does not solve the problem completely, but would help minimizing the impact.

**Comment by PVince81** [comment]
@mmattel an occ command like `occ apps:check-version` could help after the fact. However here I'm looking at ways to do it **before the upgrade** so that admins can prepare their local env to already have the upgraded apps there and avoid further service disruption. A command that identifies what shipped apps (shipped as in "part of bundle") could help. Best is of course a separate apps folder.

**Comment by PVince81** [comment]
Another idea:

1. before the upgrade: admin runs `occ apps:list` and takes note of versions
1. admin downloads **all** the available apps from marketplace regardless of upgraded or not (unless they know which ones they upgraded)
1. do the tarball swap / extraction
1. copy the downloaded apps into "apps" after deleting the previous ones

This would remove the need to know which apps were upgraded and just have the admin download all of them... It's more manual but maybe less confusing...

**Comment by PVince81** [comment]
we could also add a note that this is only needed if the deployment doesn't use a separate apps folder (many already do)...

**Comment by PVince81** [comment]
I think we should provide a list of bundled app versions per bundle release, so admins just can have a look at said list.

**Comment by PVince81** [comment]
some suggestion for the docs if we have the above:

1. before upgrade: check whether your setup has a single "apps" folder (note: this is not recommended as it would mix bundled apps with upgraded apps, see XYZ for instructions about setting up apps-external, etc). If single "apps" folder:
    1. run `occ apps:list` and compare versions with the published (TODO) list of bundled app versions
    1. for each app which is more recent than the bundle, copy the app to a separate temporary folder "apps-upgraded"
    1. run upgrade
    1. for each entry in "apps-upgraded", delete the folder "apps/$appid" and copy "apps-upgraded/$appid" into "apps".

for those with separate writable apps folder "apps-external": nothing to do but run upgrade as usual

**Comment by PVince81** [comment]
I'd also suggest we delete the "standard upgrade" from https://doc.owncloud.com/server/admin_manual/maintenance/manual_upgrade.html#the-standard-upgrade and keep only "power user" as it's more reliable and more compatible with the above apps concept.

It would be difficult to inject the above instructions into the standard upgrade.

Plan:

- [ ] adjust marketing communication to always publish the list of bundled apps and versions in a place we can link to
- [ ] delete standard upgrade, keep only "power user upgrade" and rename to "standard upgrade"
- [ ] add pre-upgrade step with instructions from https://github.com/owncloud/docs/issues/828#issuecomment-476591748
- [ ] add post-update step with the rest of instructions from https://github.com/owncloud/docs/issues/828#issuecomment-476591748 related to copying back the apps
- [ ] raise ticket to document apps-external (if not already) where we can point instructions to. migration from single apps folder to multiple apps currently unclear, to be written in the future

does that make sense ?

**Comment by PVince81** [comment]
cc @pako81 @cdamken would that help with support as well ?

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/docs/pull/829

it is currently assuming that the bundle's app versions are known.
we can then decide to make this information clearer in our release communication

**Comment by PVince81** [comment]
obsolete, we changed the bundle. bundles will not comply with SemVer
