### ISSUE TITLE
Augment the build process

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#96]
## TODO

- [ ] Dead/broken link checker (@mmattel)
- [ ] rST formatting checker (if there is any leftover rST formatting)
- [ ] InvalidLinks - Check for invalid Xrefs
- [ ] AsciiDoc Linter - To check AsciiDoc syntax. `asciidoctor -o /dev/null sample.adoc` will output errors and warnings, should files be invalid.
- [ ] LanguageTool - To check grammar issues
- [ ] SpaceConsistency - To check for unnecessary white space and newlines

**Comment by settermjd** [comment]
I've created [a small rST formatting checker script](https://github.com/settermjd/antora-build-checker-tools). I hope it helps make the build process simpler. Perhaps I should have written it in Node, as that's what Antora's build with.

**Comment by michaelstingl** [comment]
outdated
