### ISSUE TITLE
Document Search

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs#98]
## TODO

- [ ] ~~Algolia subscription (need to talk with @pmaier1)~~
- [ ] ~~Write JavaScript search script~~
- [X] Update docs theme/template

This is being implemented by #189.

**Comment by tboerger** [comment]
If we don't get the paid service we could also try to integrate something like bleve search or maybe https://gist.github.com/eddiewebb/735feb48f50f0ddd65ae5606a1cb41ae also works for antora.

**Comment by tboerger** [comment]
Besides the Hugo example I have created an issue upstream: https://gitlab.com/antora/antora/issues/312

**Comment by settermjd** [comment]
Thanks for creating the issue. I had a read of it, which was pretty enlightening.

**Comment by tboerger** [comment]
I guess we won't need Algolia and upstream is aware of that and working on a native solution.

**Comment by settermjd** [comment]
We are?

**Comment by tboerger** [comment]
> We are?

What do you mean?

**Comment by settermjd** [comment]
https://github.com/owncloud/docs/issues/98#issuecomment-425446022 - we're working on a native solution.

**Comment by voroyam** [comment]
10 days - any progress?

**Comment by settermjd** [comment]
Almost there, but time's not been my friend.

**Comment by mmattel** [comment]
Come on, the day has 24h, what are you spending the other minutes for 😃 (just kidding...)

**Comment by settermjd** [comment]
Oh, ha ha!

**Comment by felixboehm** [comment]
@settermjd have you checked if there is server side lunr?
Loading the index files from client side seems too slow,
so asking a service that provides a list with links would make sense.

**Comment by settermjd** [comment]
Sorry that I missed your comment, @felixboehm. As soon as @tboerger's back, the Algolia integration can be finished up. In testing, it's working excellently.

**Comment by michaelstingl** [comment]
No Algolia, @tboerger is working on a solution.
